#!/usr/bin/env bash

P2PA_CRONJOBS_DIR=/home/cronjobs
P2PA_CRONJOBS_LOG_DIR=${P2PA_CRONJOBS_DIR}/logs

export P2PA_CRONJOBS_DIR P2PA_CRONJOBS_LOG_DIR

P2PA_WEBAPP_DIR=/home/web
P2PA_DJANGOAPP_DIR=${P2PA_WEBAPP_DIR}/service

export P2PA_WEBAPP_DIR P2PA_DJANGOAPP_DIR

export PATH=${PATH}:${P2PA_CRONJOBS_DIR}/bin
export PYTHONPATH=${PYTHONPATH}:${P2PA_CRONJOBS_DIR}/packages:${P2PA_DJANGOAPP_DIR}
